In [4]:
from tcn import compiled_tcn
from tcn import preprocess_tts

import numpy as np
import pandas as pd


In [77]:
X = pd.read_csv("train1-0.csv")
Y = pd.read_csv("answer1-0.csv")

In [78]:
X_train = preprocess_tts.preprocess_x(X)

In [79]:
X_train.values.shape

(28, 15)

In [80]:
Y_train = np.array([float(Y.loc[66][1])])

In [81]:
Y_train.shape

(1,)

In [82]:
X_train = np.transpose(X_train.values)

In [84]:
X_train = X_train.reshape(1,15,28)

In [85]:
X_train.shape

(1, 15, 28)

In [86]:
X_train = np.asarray(X_train).astype(np.float32)

In [87]:
model = compiled_tcn(return_sequences=False,
                             num_feat=28,
                             nb_filters=24,
                             num_classes=0,
                             kernel_size=8,
                             dilations=[2 ** i for i in range(9)],
                             nb_stacks=1,
                             max_len=15,
                             use_skip_connections=True,
                             regression=True,
                             dropout_rate=0,
                             output_len=1)

x.shape= (None, 24)
model.x = (None, 15, 28)
model.y = (None, 1)


In [88]:
model.fit(X_train, Y_train, batch_size=1, epochs=1)

Train on 1 samples
1/1 [==============================] - 4s 4s/sample - loss: 6400.2173


In [60]:
A = np.array([[2,3],[4,2],[5,5]])

In [61]:
A.shape

(3, 2)

In [62]:
A

array([[2, 3],
       [4, 2],
       [5, 5]])

In [90]:
np.transpose(A)

array([[2, 4, 5],
       [3, 2, 5]])

In [91]:
B = A.copy()

In [93]:
B.shape

(3, 2)

In [94]:
B = B.reshape(1,3,2)
A = A.reshape(1,3,2)

In [104]:
np.concatenate([A,B])[0] == A 

array([[[ True,  True],
        [ True,  True],
        [ True,  True]]])